#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
VAFQMC configuration for AFQMC_hamiltonian_0_53.pkl
Generated by vafqmc-afqmc-model-editor
"""
import os
import sys
sys.path.insert(0, "/home/zzkj/Zhi-Yu_Xiao/lib/tethys-master/tethys-master")

import hafqmc.train
import hafqmc.config

# os.environ["HAMIL_TYPE"] = "hubbard"
os.environ["HAMIL_TYPE"] = "molecular"

os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"   
        

cfg = hafqmc.config.example()

cfg.restart.hamiltonian = "femoco_RHF.pkl"

# cfg.ansatz.type = "hubbard"
cfg.ansatz.type = "normal"

cfg.log.stat_freq = 1
cfg.log.rdm_freq = 0
cfg.log.ckpt_freq = 500

cfg.ansatz.wfn_spinmix = True
cfg.ansatz.propagators[0].max_nhs = 100
cfg.ansatz.propagators[0].aux_network = None
cfg.ansatz.propagators[0].init_tsteps = [0.01] * 1
cfg.ansatz.propagators[0].sqrt_tsvpar = True
cfg.ansatz.propagators[0].init_random = 0.001
cfg.ansatz.propagators[0].hermite_ops = False
cfg.ansatz.propagators[0].mf_subtract = True
cfg.ansatz.propagators[0].spin_mixing = True
cfg.ansatz.propagators[0].expm_option = ["scan", 2, 1]

cfg.optim.optimizer = "adabelief"
cfg.optim.grad_clip = 1.
cfg.optim.iteration = 10000
cfg.optim.lr.start = 0.0003
cfg.optim.lr.delay = 5000
cfg.optim.lr.decay = 1.0

cfg.sample.batch = 1000
cfg.sample.sampler = {"name": "hmc", "dt": 0.1, "length": 1.}
cfg.sample.burn_in = 100

cfg.loss.sign_factor = 999.9

cfg.seed = 1
cfg.log.level = "info"

if __name__ == "__main__":
    hafqmc.train.train(cfg)